//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Development_CW1.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConverterGameDBEntities : DbContext
    {
        public ConverterGameDBEntities()
            : base("name=ConverterGameDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usernames> Usernames { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameData> GameDatas { get; set; }
    }
}
