//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enterprise_Development_CW1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameData
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public string FromType { get; set; }
        public string ToType { get; set; }
        public string FromValue { get; set; }
        public string ToValue { get; set; }
        public string GameString { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
